/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlink from "./chainlink";
export type { chainlink };
import type * as functionconsumerSol from "./functionconsumer.sol";
export type { functionconsumerSol };
export type { AgroAICore } from "./AgroAICore";
export type { AgroAIToken } from "./AgroAIToken";
